[package]
name = "cargo-workspace-sync"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
cargo_metadata = "0.17.0"
clap = { version = "4.4.2", features = ["derive", "cargo"] }

[dev-dependencies]
tempfile = "3.8.0"
